# Site settings
title: Emupedia
email: contact@emupedia.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emupedia.net" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
# Exclude these files from production site
exclude:
  - .gitignore
  - CNAME
whitelist:
  - jekyll-watch
  - jekyll-textile-converter
  - jekyll-sass-converter
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
gems:
  - jekyll-watch
  - jekyll-textile-converter
  - jekyll-sass-converter
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji